#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# setup-new-mac.sh
# Auto-generated migration script
#
# HOW TO TRANSFER:
#  1. Upload the entire new-mac-setup/ folder to Google Drive
#  2. On the new Mac, download it from Drive to ~/Desktop/
#  3. Run:
#       cd ~/Desktop/new-mac-setup
#       chmod +x setup-new-mac.sh
#       ./setup-new-mac.sh
#
#  NOTE: Do NOT upload SECRETS_FOR_PASSWORD_MANAGER.md to Google Drive.
#        Save those to 1Password first, then delete the file.
###############################################################################

DRY_RUN=false
ACCEPT_ALL=false
ACCEPT_LIST=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=true; shift ;;
    --yes|-y) ACCEPT_ALL=true; shift ;;
    --accept)
      ACCEPT_LIST="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: $0 [--dry-run] [--yes] [--accept ITEMS]"
      echo ""
      echo "  --dry-run        Preview what would be installed without making changes"
      echo "  --yes, -y        Auto-accept all prompts"
      echo "  --accept ITEMS   Auto-accept items matching comma-separated list"
      echo "                   Example: --accept 'Slack,Chrome,1Password'"
      exit 0 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# ── Sudo Keepalive ──────────────────────────────────────────────────────────
if [[ "$DRY_RUN" != true ]]; then
  echo "This script needs your password once to avoid repeated prompts."
  sudo -v
  while true; do sudo -n true; sleep 50; kill -0 "$$" || exit; done 2>/dev/null &
  SUDO_KEEPALIVE_PID=$!
  trap 'kill $SUDO_KEEPALIVE_PID 2>/dev/null' EXIT
fi

# ── Colors & Counters ──────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'
CYAN='\033[0;36m'; BOLD='\033[1m'; GRAY='\033[0;90m'; NC='\033[0m'
INSTALLED=0; SKIPPED=0; FAILED=0

banner()  { echo -e "\n${CYAN}${BOLD}=== $1 ===${NC}\n"; }
success() { echo -e "  ${GREEN}+${NC} $1"; INSTALLED=$((INSTALLED + 1)); }
skip()    { echo -e "  ${YELLOW}>${NC} $1"; SKIPPED=$((SKIPPED + 1)); }
fail()    { echo -e "  ${RED}!${NC} $1"; FAILED=$((FAILED + 1)); }
dry()     { echo -e "  ${GRAY}[dry-run]${NC} $1"; INSTALLED=$((INSTALLED + 1)); }

prompt_yn() {
  local msg="$1"
  if [[ "$DRY_RUN" == true ]]; then
    echo -e "${GRAY}[dry-run]${NC} $msg"
    return 0
  fi
  if [[ "$ACCEPT_ALL" == true ]]; then
    echo -e "  ${GREEN}[auto-yes]${NC} $msg"
    return 0
  fi
  if [[ -n "$ACCEPT_LIST" ]]; then
    local _msg_lower _item_lower
    _msg_lower=$(echo "$msg" | tr '[:upper:]' '[:lower:]')
    IFS=',' read -ra _accept_items <<< "$ACCEPT_LIST"
    for _accept_item in "${_accept_items[@]}"; do
      _accept_item=$(echo "$_accept_item" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
      _item_lower=$(echo "$_accept_item" | tr '[:upper:]' '[:lower:]')
      if [[ -n "$_item_lower" && "$_msg_lower" == *"$_item_lower"* ]]; then
        echo -e "  ${GREEN}[auto-yes]${NC} $msg"
        return 0
      fi
    done
  fi
  read -rp "  Install $msg? [y/N] " ans
  [[ "$ans" =~ ^[Yy]$ ]]
}

append_to_zshrc() {
  local line="$1"
  if ! grep -qF "$line" "$HOME/.zshrc" 2>/dev/null; then
    echo "$line" >> "$HOME/.zshrc"
  fi
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIGS_DIR="$SCRIPT_DIR/migration-configs"

if [[ "$DRY_RUN" != true ]] && [ ! -d "$CONFIGS_DIR" ]; then
  echo -e "${RED}ERROR: migration-configs/ directory not found next to this script.${NC}"
  echo "Expected at: $CONFIGS_DIR"
  exit 1
fi

if [[ "$DRY_RUN" == true ]]; then
  echo -e "${GRAY}=== DRY RUN MODE — no changes will be made ===${NC}"
  echo ""
fi

# Generated by dotfiles-sync (SHA)
# Source machine: HOST
# Generated: TIMESTAMP

echo ""
echo "=========================================="
echo "  Migration script from: HOST
echo "  Generated: DATE"
echo "  Generator version: SHA"
echo "=========================================="
echo ""

###############################################################################
# Shell Configuration
###############################################################################
banner "Shell Configuration"

if prompt_yn "~/.zshrc (full replacement)"; then
  if [[ "$DRY_RUN" == true ]]; then
    dry "Would write ~/.zshrc"
  else
    cat > "$HOME/.zshrc" << 'ZSHRC_EOF'
# Oh-My-Zsh configuration
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Aliases
alias gs='git status'
alias ll='ls -la'

# Exports
export EDITOR=vim
export API_KEY="CHANGEME"
export GOPATH="$HOME/go"

# PATH
export PATH="$HOME/.local/bin:$PATH"

# Functions
greet() {
  echo "Hello, $1"
}
ZSHRC_EOF
    success "~/.zshrc"
  fi
else
  skip "~/.zshrc"
fi

if prompt_yn "~/.zprofile"; then
  if [[ "$DRY_RUN" == true ]]; then
    dry "Would write ~/.zprofile"
  else
    cat > "$HOME/.zprofile" << 'SHELLFILE_EOF'
eval "$(/opt/homebrew/bin/brew shellenv)"
export HOMEBREW_NO_ANALYTICS=1
SHELLFILE_EOF
    success "~/.zprofile"
  fi
else
  skip "~/.zprofile"
fi

###############################################################################
# Inject Secrets from Password Manager
###############################################################################
banner "Inject Secrets from Password Manager"

echo -e "${BOLD}For each prompt below, paste the value from your password manager.${NC}"
echo -e "${BOLD}Press Enter to skip any item.${NC}"
echo ""

echo -e "${CYAN}API_KEY${NC}"
if [[ "$DRY_RUN" == true ]]; then
  dry "Would prompt for API_KEY"
elif [[ "$ACCEPT_ALL" == true ]]; then
  skip "API_KEY (auto-yes cannot fill secrets — enter manually later)"
else
  read -rsp "  Value (hidden): " _val
  echo
fi
if [[ "$DRY_RUN" != true && "$ACCEPT_ALL" != true && -n "${_val:-}" ]]; then
  for _f in "$HOME/.zshrc" "$HOME/.zprofile"; do
    if [[ -f "$_f" ]]; then
      _content=$(cat "$_f")
      printf '%s\n' "${_content//export API_KEY=\"CHANGEME\"/export API_KEY=\"$_val\"}" > "$_f"
      _content=$(cat "$_f")
      printf '%s\n' "${_content//export API_KEY=CHANGEME/export API_KEY=$_val}" > "$_f"
    fi
  done
  success "Injected API_KEY"
else
  skip "API_KEY"
fi

echo ""
echo -e "${YELLOW}For MCP server tokens (Claude Code + Cursor), edit these files manually:${NC}"
echo -e "  ${CYAN}~/.claude/.mcp.json${NC}"
echo -e "  ${CYAN}~/.cursor/mcp.json${NC}"
echo -e "${YELLOW}Replace any remaining 'CHANGEME' values with your actual tokens.${NC}"
echo ""

###############################################################################
# Git Configuration
###############################################################################
banner "Git Configuration"

if prompt_yn "~/.gitconfig"; then
  if [[ "$DRY_RUN" == true ]]; then
    dry "Would write ~/.gitconfig"
  else
    cat > "$HOME/.gitconfig" << 'GITCONFIG_EOF'
[user]
	name = Test User
	email = test@example.com
[core]
	editor = vim
GITCONFIG_EOF
    success "~/.gitconfig"
  fi
else
  skip "~/.gitconfig"
fi

###############################################################################
# Summary
###############################################################################
banner "Summary"

echo ""
echo "=========================================="
if [[ "$DRY_RUN" == true ]]; then
  echo -e "  ${GRAY}DRY RUN SUMMARY${NC}"
  echo -e "  ${GREEN}Would install:  $INSTALLED${NC}"
  echo -e "  ${YELLOW}Would skip:     $SKIPPED${NC}"
  echo -e "  ${RED}Would fail:     $FAILED${NC}"
  echo ""
  echo "  Run without --dry-run to apply changes."
else
  echo -e "  ${GREEN}Installed: $INSTALLED${NC}"
  echo -e "  ${YELLOW}Skipped:   $SKIPPED${NC}"
  echo -e "  ${RED}Failed:    $FAILED${NC}"
fi
echo "=========================================="
echo ""
if [[ "$DRY_RUN" != true ]]; then
  echo -e "${BOLD}Done! Restart your terminal to pick up shell changes.${NC}"
fi
