#!/usr/bin/env bash
# lib/emit-preamble.sh — Writes the install script header
# Sourced by generate-setup.sh; do not execute directly.

emit_preamble() {
  local gen_version gen_date gen_host
  gen_version=$(git -C "$SCRIPT_DIR" rev-parse --short HEAD 2>/dev/null || echo "unknown")
  gen_date=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  gen_host=$(hostname -s)

  umask 077

  cat > "$SCRIPT_FILE" << 'PREAMBLE'
#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# setup-new-mac.sh
# Auto-generated migration script
#
# HOW TO TRANSFER:
#  1. Upload the entire new-mac-setup/ folder to Google Drive
#  2. On the new Mac, download it from Drive to ~/Desktop/
#  3. Run:
#       cd ~/Desktop/new-mac-setup
#       chmod +x setup-new-mac.sh
#       ./setup-new-mac.sh
#
#  NOTE: Do NOT upload SECRETS_FOR_PASSWORD_MANAGER.md to Google Drive.
#        Save those to 1Password first, then delete the file.
###############################################################################

DRY_RUN=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=true; shift ;;
    -h|--help)
      echo "Usage: $0 [--dry-run]"
      echo "  --dry-run  Preview what would be installed without making changes"
      exit 0 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# ── Sudo Keepalive ──────────────────────────────────────────────────────────
if [[ "$DRY_RUN" != true ]]; then
  echo "This script needs your password once to avoid repeated prompts."
  sudo -v
  while true; do sudo -n true; sleep 50; kill -0 "$$" || exit; done 2>/dev/null &
  SUDO_KEEPALIVE_PID=$!
  trap 'kill $SUDO_KEEPALIVE_PID 2>/dev/null' EXIT
fi

# ── Colors & Counters ──────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'
CYAN='\033[0;36m'; BOLD='\033[1m'; GRAY='\033[0;90m'; NC='\033[0m'
INSTALLED=0; SKIPPED=0; FAILED=0

banner()  { echo -e "\n${CYAN}${BOLD}=== $1 ===${NC}\n"; }
success() { echo -e "  ${GREEN}+${NC} $1"; ((INSTALLED++)); }
skip()    { echo -e "  ${YELLOW}>${NC} $1"; ((SKIPPED++)); }
fail()    { echo -e "  ${RED}!${NC} $1"; ((FAILED++)); }
dry()     { echo -e "  ${GRAY}[dry-run]${NC} $1"; ((INSTALLED++)); }

prompt_yn() {
  local msg="$1"
  if [[ "$DRY_RUN" == true ]]; then
    echo -e "${GRAY}[dry-run]${NC} $msg"
    return 0
  fi
  read -rp "  Install $msg? [y/N] " ans
  [[ "$ans" =~ ^[Yy]$ ]]
}

append_to_zshrc() {
  local line="$1"
  if ! grep -qF "$line" "$HOME/.zshrc" 2>/dev/null; then
    echo "$line" >> "$HOME/.zshrc"
  fi
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIGS_DIR="$SCRIPT_DIR/migration-configs"

if [[ "$DRY_RUN" != true ]] && [ ! -d "$CONFIGS_DIR" ]; then
  echo -e "${RED}ERROR: migration-configs/ directory not found next to this script.${NC}"
  echo "Expected at: $CONFIGS_DIR"
  exit 1
fi

if [[ "$DRY_RUN" == true ]]; then
  echo -e "${GRAY}=== DRY RUN MODE — no changes will be made ===${NC}"
  echo ""
fi
PREAMBLE

  # Append version stamp (these expand at generation time)
  cat >> "$SCRIPT_FILE" << EOF

# Generated by dotfiles-sync ($gen_version)
# Source machine: $gen_host
# Generated: $gen_date

echo ""
echo "=========================================="
echo "  Migration script from: $gen_host"
echo "  Generated: $(date +%Y-%m-%d)"
echo "  Generator version: $gen_version"
echo "=========================================="
echo ""
EOF
}
